import Foundation

/// A curated list of major cities (name + representative coordinate) for the no-permission manual
/// location override. Deliberately includes cities that differ meaningfully from their time zone's
/// representative coordinate (e.g. San Francisco/Seattle within America/Los_Angeles).
public enum MajorCities {
    public struct City: Hashable, Sendable, Identifiable {
        public let name: String
        public let coordinate: TimeZoneCoordinates.Coordinate
        public var id: String { name }

        public init(name: String, coordinate: TimeZoneCoordinates.Coordinate) {
            self.name = name
            self.coordinate = coordinate
        }
    }

    /// ~100 major cities across regions, alphabetical by name.
    public static let all: [City] = [
        City(name: "Amsterdam", coordinate: .init(latitude: 52.37, longitude: 4.90)),
        City(name: "Athens", coordinate: .init(latitude: 37.98, longitude: 23.73)),
        City(name: "Atlanta", coordinate: .init(latitude: 33.75, longitude: -84.39)),
        City(name: "Auckland", coordinate: .init(latitude: -36.85, longitude: 174.76)),
        City(name: "Austin", coordinate: .init(latitude: 30.27, longitude: -97.74)),
        City(name: "Bangkok", coordinate: .init(latitude: 13.76, longitude: 100.50)),
        City(name: "Barcelona", coordinate: .init(latitude: 41.39, longitude: 2.17)),
        City(name: "Beijing", coordinate: .init(latitude: 39.90, longitude: 116.41)),
        City(name: "Beirut", coordinate: .init(latitude: 33.89, longitude: 35.50)),
        City(name: "Bengaluru", coordinate: .init(latitude: 12.97, longitude: 77.59)),
        City(name: "Berlin", coordinate: .init(latitude: 52.52, longitude: 13.40)),
        City(name: "Bogotá", coordinate: .init(latitude: 4.71, longitude: -74.07)),
        City(name: "Boston", coordinate: .init(latitude: 42.36, longitude: -71.06)),
        City(name: "Brisbane", coordinate: .init(latitude: -27.47, longitude: 153.03)),
        City(name: "Brussels", coordinate: .init(latitude: 50.85, longitude: 4.35)),
        City(name: "Budapest", coordinate: .init(latitude: 47.50, longitude: 19.04)),
        City(name: "Buenos Aires", coordinate: .init(latitude: -34.61, longitude: -58.38)),
        City(name: "Cairo", coordinate: .init(latitude: 30.04, longitude: 31.24)),
        City(name: "Calgary", coordinate: .init(latitude: 51.05, longitude: -114.07)),
        City(name: "Cape Town", coordinate: .init(latitude: -33.92, longitude: 18.42)),
        City(name: "Casablanca", coordinate: .init(latitude: 33.57, longitude: -7.59)),
        City(name: "Charlotte", coordinate: .init(latitude: 35.23, longitude: -80.84)),
        City(name: "Chennai", coordinate: .init(latitude: 13.08, longitude: 80.27)),
        City(name: "Chicago", coordinate: .init(latitude: 41.85, longitude: -87.65)),
        City(name: "Copenhagen", coordinate: .init(latitude: 55.68, longitude: 12.57)),
        City(name: "Dallas", coordinate: .init(latitude: 32.78, longitude: -96.80)),
        City(name: "Delhi", coordinate: .init(latitude: 28.61, longitude: 77.21)),
        City(name: "Denver", coordinate: .init(latitude: 39.74, longitude: -104.98)),
        City(name: "Doha", coordinate: .init(latitude: 25.29, longitude: 51.53)),
        City(name: "Dubai", coordinate: .init(latitude: 25.20, longitude: 55.27)),
        City(name: "Dublin", coordinate: .init(latitude: 53.35, longitude: -6.26)),
        City(name: "Edinburgh", coordinate: .init(latitude: 55.95, longitude: -3.19)),
        City(name: "Frankfurt", coordinate: .init(latitude: 50.11, longitude: 8.68)),
        City(name: "Guangzhou", coordinate: .init(latitude: 23.13, longitude: 113.26)),
        City(name: "Hamburg", coordinate: .init(latitude: 53.55, longitude: 10.00)),
        City(name: "Helsinki", coordinate: .init(latitude: 60.17, longitude: 24.94)),
        City(name: "Hong Kong", coordinate: .init(latitude: 22.32, longitude: 114.17)),
        City(name: "Houston", coordinate: .init(latitude: 29.76, longitude: -95.37)),
        City(name: "Hyderabad", coordinate: .init(latitude: 17.39, longitude: 78.49)),
        City(name: "Istanbul", coordinate: .init(latitude: 41.01, longitude: 28.98)),
        City(name: "Jakarta", coordinate: .init(latitude: -6.21, longitude: 106.85)),
        City(name: "Johannesburg", coordinate: .init(latitude: -26.20, longitude: 28.04)),
        City(name: "Karachi", coordinate: .init(latitude: 24.86, longitude: 67.01)),
        City(name: "Kuala Lumpur", coordinate: .init(latitude: 3.14, longitude: 101.69)),
        City(name: "Kyiv", coordinate: .init(latitude: 50.45, longitude: 30.52)),
        City(name: "Lagos", coordinate: .init(latitude: 6.52, longitude: 3.38)),
        City(name: "Las Vegas", coordinate: .init(latitude: 36.17, longitude: -115.14)),
        City(name: "Lima", coordinate: .init(latitude: -12.05, longitude: -77.04)),
        City(name: "Lisbon", coordinate: .init(latitude: 38.72, longitude: -9.14)),
        City(name: "London", coordinate: .init(latitude: 51.51, longitude: -0.13)),
        City(name: "Los Angeles", coordinate: .init(latitude: 34.05, longitude: -118.24)),
        City(name: "Madrid", coordinate: .init(latitude: 40.42, longitude: -3.70)),
        City(name: "Manchester", coordinate: .init(latitude: 53.48, longitude: -2.24)),
        City(name: "Manila", coordinate: .init(latitude: 14.60, longitude: 120.98)),
        City(name: "Melbourne", coordinate: .init(latitude: -37.81, longitude: 144.96)),
        City(name: "Mexico City", coordinate: .init(latitude: 19.43, longitude: -99.13)),
        City(name: "Miami", coordinate: .init(latitude: 25.76, longitude: -80.19)),
        City(name: "Milan", coordinate: .init(latitude: 45.46, longitude: 9.19)),
        City(name: "Montreal", coordinate: .init(latitude: 45.50, longitude: -73.57)),
        City(name: "Moscow", coordinate: .init(latitude: 55.76, longitude: 37.62)),
        City(name: "Mumbai", coordinate: .init(latitude: 19.08, longitude: 72.88)),
        City(name: "Munich", coordinate: .init(latitude: 48.14, longitude: 11.58)),
        City(name: "Nagoya", coordinate: .init(latitude: 35.18, longitude: 136.91)),
        City(name: "Nairobi", coordinate: .init(latitude: -1.29, longitude: 36.82)),
        City(name: "New York", coordinate: .init(latitude: 40.71, longitude: -74.01)),
        City(name: "Osaka", coordinate: .init(latitude: 34.69, longitude: 135.50)),
        City(name: "Oslo", coordinate: .init(latitude: 59.91, longitude: 10.75)),
        City(name: "Paris", coordinate: .init(latitude: 48.86, longitude: 2.35)),
        City(name: "Perth", coordinate: .init(latitude: -31.95, longitude: 115.86)),
        City(name: "Philadelphia", coordinate: .init(latitude: 39.95, longitude: -75.17)),
        City(name: "Phoenix", coordinate: .init(latitude: 33.45, longitude: -112.07)),
        City(name: "Portland", coordinate: .init(latitude: 45.52, longitude: -122.68)),
        City(name: "Prague", coordinate: .init(latitude: 50.08, longitude: 14.44)),
        City(name: "Rio de Janeiro", coordinate: .init(latitude: -22.91, longitude: -43.17)),
        City(name: "Rome", coordinate: .init(latitude: 41.90, longitude: 12.50)),
        City(name: "San Diego", coordinate: .init(latitude: 32.72, longitude: -117.16)),
        City(name: "San Francisco", coordinate: .init(latitude: 37.77, longitude: -122.42)),
        City(name: "Santiago", coordinate: .init(latitude: -33.45, longitude: -70.67)),
        City(name: "São Paulo", coordinate: .init(latitude: -23.55, longitude: -46.63)),
        City(name: "Seattle", coordinate: .init(latitude: 47.61, longitude: -122.33)),
        City(name: "Seoul", coordinate: .init(latitude: 37.57, longitude: 126.98)),
        City(name: "Shanghai", coordinate: .init(latitude: 31.23, longitude: 121.47)),
        City(name: "Shenzhen", coordinate: .init(latitude: 22.54, longitude: 114.06)),
        City(name: "Singapore", coordinate: .init(latitude: 1.35, longitude: 103.82)),
        City(name: "Stockholm", coordinate: .init(latitude: 59.33, longitude: 18.07)),
        City(name: "Sydney", coordinate: .init(latitude: -33.87, longitude: 151.21)),
        City(name: "Taipei", coordinate: .init(latitude: 25.03, longitude: 121.56)),
        City(name: "Tel Aviv", coordinate: .init(latitude: 32.08, longitude: 34.78)),
        City(name: "Tokyo", coordinate: .init(latitude: 35.68, longitude: 139.69)),
        City(name: "Toronto", coordinate: .init(latitude: 43.65, longitude: -79.38)),
        City(name: "Valencia", coordinate: .init(latitude: 39.47, longitude: -0.38)),
        City(name: "Vancouver", coordinate: .init(latitude: 49.28, longitude: -123.12)),
        City(name: "Vienna", coordinate: .init(latitude: 48.21, longitude: 16.37)),
        City(name: "Warsaw", coordinate: .init(latitude: 52.23, longitude: 21.01)),
        City(name: "Wellington", coordinate: .init(latitude: -41.29, longitude: 174.78)),
        City(name: "Zurich", coordinate: .init(latitude: 47.38, longitude: 8.54)),
    ]
}
