import Foundation

/// A curated list of major cities (name + representative coordinate) for the no-permission manual
/// location override. Deliberately includes cities that differ meaningfully from their time zone's
/// representative coordinate (e.g. San Francisco/Seattle within America/Los_Angeles).
public enum MajorCities {
    public struct City: Hashable, Sendable, Identifiable {
        public let name: String
        public let coordinate: TimeZoneCoordinates.Coordinate
        public let timeZone: String
        public var id: String { name }

        public init(name: String, coordinate: TimeZoneCoordinates.Coordinate, timeZone: String) {
            self.name = name
            self.coordinate = coordinate
            self.timeZone = timeZone
        }
    }

    /// ~100 major cities across regions, alphabetical by name.
    public static let all: [City] = [
        City(name: "Albany", coordinate: .init(latitude: 42.65, longitude: -73.75), timeZone: "America/New_York"),
        City(name: "Albuquerque", coordinate: .init(latitude: 35.08, longitude: -106.65), timeZone: "America/Denver"),
        City(name: "Amsterdam", coordinate: .init(latitude: 52.37, longitude: 4.90), timeZone: "Europe/Amsterdam"),
        City(name: "Anchorage", coordinate: .init(latitude: 61.22, longitude: -149.90), timeZone: "America/Anchorage"),
        City(name: "Ann Arbor", coordinate: .init(latitude: 42.28, longitude: -83.74), timeZone: "America/Detroit"),
        City(name: "Athens", coordinate: .init(latitude: 37.98, longitude: 23.73), timeZone: "Europe/Athens"),
        City(name: "Atlanta", coordinate: .init(latitude: 33.75, longitude: -84.39), timeZone: "America/New_York"),
        City(name: "Auckland", coordinate: .init(latitude: -36.85, longitude: 174.76), timeZone: "Pacific/Auckland"),
        City(name: "Austin", coordinate: .init(latitude: 30.27, longitude: -97.74), timeZone: "America/Chicago"),
        City(name: "Bakersfield", coordinate: .init(latitude: 35.37, longitude: -119.02), timeZone: "America/Los_Angeles"),
        City(name: "Baltimore", coordinate: .init(latitude: 39.29, longitude: -76.61), timeZone: "America/New_York"),
        City(name: "Bangkok", coordinate: .init(latitude: 13.76, longitude: 100.50), timeZone: "Asia/Bangkok"),
        City(name: "Barcelona", coordinate: .init(latitude: 41.39, longitude: 2.17), timeZone: "Europe/Madrid"),
        City(name: "Beijing", coordinate: .init(latitude: 39.90, longitude: 116.41), timeZone: "Asia/Shanghai"),
        City(name: "Beirut", coordinate: .init(latitude: 33.89, longitude: 35.50), timeZone: "Asia/Beirut"),
        City(name: "Bengaluru", coordinate: .init(latitude: 12.97, longitude: 77.59), timeZone: "Asia/Kolkata"),
        City(name: "Berlin", coordinate: .init(latitude: 52.52, longitude: 13.40), timeZone: "Europe/Berlin"),
        City(name: "Birmingham", coordinate: .init(latitude: 33.52, longitude: -86.81), timeZone: "America/Chicago"),
        City(name: "Bogotá", coordinate: .init(latitude: 4.71, longitude: -74.07), timeZone: "America/Bogota"),
        City(name: "Boise", coordinate: .init(latitude: 43.62, longitude: -116.21), timeZone: "America/Boise"),
        City(name: "Boston", coordinate: .init(latitude: 42.36, longitude: -71.06), timeZone: "America/New_York"),
        City(name: "Brisbane", coordinate: .init(latitude: -27.47, longitude: 153.03), timeZone: "Australia/Brisbane"),
        City(name: "Brussels", coordinate: .init(latitude: 50.85, longitude: 4.35), timeZone: "Europe/Brussels"),
        City(name: "Budapest", coordinate: .init(latitude: 47.50, longitude: 19.04), timeZone: "Europe/Budapest"),
        City(name: "Buenos Aires", coordinate: .init(latitude: -34.61, longitude: -58.38), timeZone: "America/Argentina/Buenos_Aires"),
        City(name: "Buffalo", coordinate: .init(latitude: 42.89, longitude: -78.88), timeZone: "America/New_York"),
        City(name: "Cairo", coordinate: .init(latitude: 30.04, longitude: 31.24), timeZone: "Africa/Cairo"),
        City(name: "Calgary", coordinate: .init(latitude: 51.05, longitude: -114.07), timeZone: "America/Edmonton"),
        City(name: "Cape Town", coordinate: .init(latitude: -33.92, longitude: 18.42), timeZone: "Africa/Johannesburg"),
        City(name: "Casablanca", coordinate: .init(latitude: 33.57, longitude: -7.59), timeZone: "Africa/Casablanca"),
        City(name: "Charleston", coordinate: .init(latitude: 32.78, longitude: -79.93), timeZone: "America/New_York"),
        City(name: "Charlotte", coordinate: .init(latitude: 35.23, longitude: -80.84), timeZone: "America/New_York"),
        City(name: "Chattanooga", coordinate: .init(latitude: 35.05, longitude: -85.31), timeZone: "America/New_York"),
        City(name: "Chennai", coordinate: .init(latitude: 13.08, longitude: 80.27), timeZone: "Asia/Kolkata"),
        City(name: "Chicago", coordinate: .init(latitude: 41.85, longitude: -87.65), timeZone: "America/Chicago"),
        City(name: "Cincinnati", coordinate: .init(latitude: 39.10, longitude: -84.51), timeZone: "America/New_York"),
        City(name: "Cleveland", coordinate: .init(latitude: 41.50, longitude: -81.69), timeZone: "America/New_York"),
        City(name: "Colorado Springs", coordinate: .init(latitude: 38.83, longitude: -104.82), timeZone: "America/Denver"),
        City(name: "Columbus", coordinate: .init(latitude: 39.96, longitude: -83.00), timeZone: "America/New_York"),
        City(name: "Copenhagen", coordinate: .init(latitude: 55.68, longitude: 12.57), timeZone: "Europe/Copenhagen"),
        City(name: "Dallas", coordinate: .init(latitude: 32.78, longitude: -96.80), timeZone: "America/Chicago"),
        City(name: "Delhi", coordinate: .init(latitude: 28.61, longitude: 77.21), timeZone: "Asia/Kolkata"),
        City(name: "Denver", coordinate: .init(latitude: 39.74, longitude: -104.98), timeZone: "America/Denver"),
        City(name: "Des Moines", coordinate: .init(latitude: 41.59, longitude: -93.62), timeZone: "America/Chicago"),
        City(name: "Doha", coordinate: .init(latitude: 25.29, longitude: 51.53), timeZone: "Asia/Qatar"),
        City(name: "Dubai", coordinate: .init(latitude: 25.20, longitude: 55.27), timeZone: "Asia/Dubai"),
        City(name: "Dublin", coordinate: .init(latitude: 53.35, longitude: -6.26), timeZone: "Europe/Dublin"),
        City(name: "Edinburgh", coordinate: .init(latitude: 55.95, longitude: -3.19), timeZone: "Europe/London"),
        City(name: "El Paso", coordinate: .init(latitude: 31.76, longitude: -106.49), timeZone: "America/Denver"),
        City(name: "Fort Worth", coordinate: .init(latitude: 32.76, longitude: -97.33), timeZone: "America/Chicago"),
        City(name: "Frankfurt", coordinate: .init(latitude: 50.11, longitude: 8.68), timeZone: "Europe/Berlin"),
        City(name: "Fresno", coordinate: .init(latitude: 36.74, longitude: -119.77), timeZone: "America/Los_Angeles"),
        City(name: "Grand Rapids", coordinate: .init(latitude: 42.96, longitude: -85.67), timeZone: "America/Detroit"),
        City(name: "Greensboro", coordinate: .init(latitude: 36.07, longitude: -79.79), timeZone: "America/New_York"),
        City(name: "Guangzhou", coordinate: .init(latitude: 23.13, longitude: 113.26), timeZone: "Asia/Shanghai"),
        City(name: "Hamburg", coordinate: .init(latitude: 53.55, longitude: 10.00), timeZone: "Europe/Berlin"),
        City(name: "Hartford", coordinate: .init(latitude: 41.76, longitude: -72.69), timeZone: "America/New_York"),
        City(name: "Helsinki", coordinate: .init(latitude: 60.17, longitude: 24.94), timeZone: "Europe/Helsinki"),
        City(name: "Hong Kong", coordinate: .init(latitude: 22.32, longitude: 114.17), timeZone: "Asia/Hong_Kong"),
        City(name: "Honolulu", coordinate: .init(latitude: 21.31, longitude: -157.86), timeZone: "Pacific/Honolulu"),
        City(name: "Houston", coordinate: .init(latitude: 29.76, longitude: -95.37), timeZone: "America/Chicago"),
        City(name: "Hyderabad", coordinate: .init(latitude: 17.39, longitude: 78.49), timeZone: "Asia/Kolkata"),
        City(name: "Indianapolis", coordinate: .init(latitude: 39.77, longitude: -86.16), timeZone: "America/Indiana/Indianapolis"),
        City(name: "Istanbul", coordinate: .init(latitude: 41.01, longitude: 28.98), timeZone: "Europe/Istanbul"),
        City(name: "Jacksonville", coordinate: .init(latitude: 30.33, longitude: -81.66), timeZone: "America/New_York"),
        City(name: "Jakarta", coordinate: .init(latitude: -6.21, longitude: 106.85), timeZone: "Asia/Jakarta"),
        City(name: "Johannesburg", coordinate: .init(latitude: -26.20, longitude: 28.04), timeZone: "Africa/Johannesburg"),
        City(name: "Kansas City", coordinate: .init(latitude: 39.10, longitude: -94.58), timeZone: "America/Chicago"),
        City(name: "Karachi", coordinate: .init(latitude: 24.86, longitude: 67.01), timeZone: "Asia/Karachi"),
        City(name: "Knoxville", coordinate: .init(latitude: 35.96, longitude: -83.92), timeZone: "America/New_York"),
        City(name: "Kuala Lumpur", coordinate: .init(latitude: 3.14, longitude: 101.69), timeZone: "Asia/Kuala_Lumpur"),
        City(name: "Kyiv", coordinate: .init(latitude: 50.45, longitude: 30.52), timeZone: "Europe/Kyiv"),
        City(name: "Lagos", coordinate: .init(latitude: 6.52, longitude: 3.38), timeZone: "Africa/Lagos"),
        City(name: "Las Vegas", coordinate: .init(latitude: 36.17, longitude: -115.14), timeZone: "America/Los_Angeles"),
        City(name: "Lexington", coordinate: .init(latitude: 38.04, longitude: -84.50), timeZone: "America/New_York"),
        City(name: "Lima", coordinate: .init(latitude: -12.05, longitude: -77.04), timeZone: "America/Lima"),
        City(name: "Lisbon", coordinate: .init(latitude: 38.72, longitude: -9.14), timeZone: "Europe/Lisbon"),
        City(name: "Little Rock", coordinate: .init(latitude: 34.75, longitude: -92.29), timeZone: "America/Chicago"),
        City(name: "London", coordinate: .init(latitude: 51.51, longitude: -0.13), timeZone: "Europe/London"),
        City(name: "Los Angeles", coordinate: .init(latitude: 34.05, longitude: -118.24), timeZone: "America/Los_Angeles"),
        City(name: "Louisville", coordinate: .init(latitude: 38.25, longitude: -85.76), timeZone: "America/Kentucky/Louisville"),
        City(name: "Madison", coordinate: .init(latitude: 43.07, longitude: -89.40), timeZone: "America/Chicago"),
        City(name: "Madrid", coordinate: .init(latitude: 40.42, longitude: -3.70), timeZone: "Europe/Madrid"),
        City(name: "Manchester", coordinate: .init(latitude: 53.48, longitude: -2.24), timeZone: "Europe/London"),
        City(name: "Manila", coordinate: .init(latitude: 14.60, longitude: 120.98), timeZone: "Asia/Manila"),
        City(name: "Melbourne", coordinate: .init(latitude: -37.81, longitude: 144.96), timeZone: "Australia/Melbourne"),
        City(name: "Memphis", coordinate: .init(latitude: 35.15, longitude: -90.05), timeZone: "America/Chicago"),
        City(name: "Mexico City", coordinate: .init(latitude: 19.43, longitude: -99.13), timeZone: "America/Mexico_City"),
        City(name: "Miami", coordinate: .init(latitude: 25.76, longitude: -80.19), timeZone: "America/New_York"),
        City(name: "Milan", coordinate: .init(latitude: 45.46, longitude: 9.19), timeZone: "Europe/Rome"),
        City(name: "Milwaukee", coordinate: .init(latitude: 43.04, longitude: -87.91), timeZone: "America/Chicago"),
        City(name: "Minneapolis", coordinate: .init(latitude: 44.98, longitude: -93.27), timeZone: "America/Chicago"),
        City(name: "Mobile", coordinate: .init(latitude: 30.69, longitude: -88.04), timeZone: "America/Chicago"),
        City(name: "Monterey", coordinate: .init(latitude: 36.60, longitude: -121.89), timeZone: "America/Los_Angeles"),
        City(name: "Montreal", coordinate: .init(latitude: 45.50, longitude: -73.57), timeZone: "America/Toronto"),
        City(name: "Moscow", coordinate: .init(latitude: 55.76, longitude: 37.62), timeZone: "Europe/Moscow"),
        City(name: "Mumbai", coordinate: .init(latitude: 19.08, longitude: 72.88), timeZone: "Asia/Kolkata"),
        City(name: "Munich", coordinate: .init(latitude: 48.14, longitude: 11.58), timeZone: "Europe/Berlin"),
        City(name: "Nagoya", coordinate: .init(latitude: 35.18, longitude: 136.91), timeZone: "Asia/Tokyo"),
        City(name: "Nairobi", coordinate: .init(latitude: -1.29, longitude: 36.82), timeZone: "Africa/Nairobi"),
        City(name: "Nashville", coordinate: .init(latitude: 36.16, longitude: -86.78), timeZone: "America/Chicago"),
        City(name: "New Orleans", coordinate: .init(latitude: 29.95, longitude: -90.07), timeZone: "America/Chicago"),
        City(name: "New York", coordinate: .init(latitude: 40.71, longitude: -74.01), timeZone: "America/New_York"),
        City(name: "Norfolk", coordinate: .init(latitude: 36.85, longitude: -76.29), timeZone: "America/New_York"),
        City(name: "Oklahoma City", coordinate: .init(latitude: 35.47, longitude: -97.52), timeZone: "America/Chicago"),
        City(name: "Omaha", coordinate: .init(latitude: 41.26, longitude: -95.93), timeZone: "America/Chicago"),
        City(name: "Orlando", coordinate: .init(latitude: 28.54, longitude: -81.38), timeZone: "America/New_York"),
        City(name: "Osaka", coordinate: .init(latitude: 34.69, longitude: 135.50), timeZone: "Asia/Tokyo"),
        City(name: "Oslo", coordinate: .init(latitude: 59.91, longitude: 10.75), timeZone: "Europe/Oslo"),
        City(name: "Paris", coordinate: .init(latitude: 48.86, longitude: 2.35), timeZone: "Europe/Paris"),
        City(name: "Perth", coordinate: .init(latitude: -31.95, longitude: 115.86), timeZone: "Australia/Perth"),
        City(name: "Philadelphia", coordinate: .init(latitude: 39.95, longitude: -75.17), timeZone: "America/New_York"),
        City(name: "Phoenix", coordinate: .init(latitude: 33.45, longitude: -112.07), timeZone: "America/Phoenix"),
        City(name: "Pittsburgh", coordinate: .init(latitude: 40.44, longitude: -79.99), timeZone: "America/New_York"),
        City(name: "Portland", coordinate: .init(latitude: 45.52, longitude: -122.68), timeZone: "America/Los_Angeles"),
        City(name: "Prague", coordinate: .init(latitude: 50.08, longitude: 14.44), timeZone: "Europe/Prague"),
        City(name: "Providence", coordinate: .init(latitude: 41.82, longitude: -71.41), timeZone: "America/New_York"),
        City(name: "Raleigh", coordinate: .init(latitude: 35.78, longitude: -78.64), timeZone: "America/New_York"),
        City(name: "Richmond", coordinate: .init(latitude: 37.54, longitude: -77.44), timeZone: "America/New_York"),
        City(name: "Rio de Janeiro", coordinate: .init(latitude: -22.91, longitude: -43.17), timeZone: "America/Sao_Paulo"),
        City(name: "Rome", coordinate: .init(latitude: 41.90, longitude: 12.50), timeZone: "Europe/Rome"),
        City(name: "Sacramento", coordinate: .init(latitude: 38.58, longitude: -121.49), timeZone: "America/Los_Angeles"),
        City(name: "Salt Lake City", coordinate: .init(latitude: 40.76, longitude: -111.89), timeZone: "America/Denver"),
        City(name: "San Antonio", coordinate: .init(latitude: 29.42, longitude: -98.49), timeZone: "America/Chicago"),
        City(name: "San Diego", coordinate: .init(latitude: 32.72, longitude: -117.16), timeZone: "America/Los_Angeles"),
        City(name: "San Francisco", coordinate: .init(latitude: 37.77, longitude: -122.42), timeZone: "America/Los_Angeles"),
        City(name: "San Jose", coordinate: .init(latitude: 37.34, longitude: -121.89), timeZone: "America/Los_Angeles"),
        City(name: "Santiago", coordinate: .init(latitude: -33.45, longitude: -70.67), timeZone: "America/Santiago"),
        City(name: "São Paulo", coordinate: .init(latitude: -23.55, longitude: -46.63), timeZone: "America/Sao_Paulo"),
        City(name: "Savannah", coordinate: .init(latitude: 32.08, longitude: -81.09), timeZone: "America/New_York"),
        City(name: "Seattle", coordinate: .init(latitude: 47.61, longitude: -122.33), timeZone: "America/Los_Angeles"),
        City(name: "Seoul", coordinate: .init(latitude: 37.57, longitude: 126.98), timeZone: "Asia/Seoul"),
        City(name: "Shanghai", coordinate: .init(latitude: 31.23, longitude: 121.47), timeZone: "Asia/Shanghai"),
        City(name: "Shenzhen", coordinate: .init(latitude: 22.54, longitude: 114.06), timeZone: "Asia/Shanghai"),
        City(name: "Singapore", coordinate: .init(latitude: 1.35, longitude: 103.82), timeZone: "Asia/Singapore"),
        City(name: "Stockholm", coordinate: .init(latitude: 59.33, longitude: 18.07), timeZone: "Europe/Stockholm"),
        City(name: "Sydney", coordinate: .init(latitude: -33.87, longitude: 151.21), timeZone: "Australia/Sydney"),
        City(name: "Taipei", coordinate: .init(latitude: 25.03, longitude: 121.56), timeZone: "Asia/Taipei"),
        City(name: "Tampa", coordinate: .init(latitude: 27.95, longitude: -82.46), timeZone: "America/New_York"),
        City(name: "Tel Aviv", coordinate: .init(latitude: 32.08, longitude: 34.78), timeZone: "Asia/Jerusalem"),
        City(name: "Tokyo", coordinate: .init(latitude: 35.68, longitude: 139.69), timeZone: "Asia/Tokyo"),
        City(name: "Toronto", coordinate: .init(latitude: 43.65, longitude: -79.38), timeZone: "America/Toronto"),
        City(name: "Tucson", coordinate: .init(latitude: 32.22, longitude: -110.97), timeZone: "America/Phoenix"),
        City(name: "Tulsa", coordinate: .init(latitude: 36.15, longitude: -95.99), timeZone: "America/Chicago"),
        City(name: "Valencia", coordinate: .init(latitude: 39.47, longitude: -0.38), timeZone: "Europe/Madrid"),
        City(name: "Vancouver", coordinate: .init(latitude: 49.28, longitude: -123.12), timeZone: "America/Vancouver"),
        City(name: "Vienna", coordinate: .init(latitude: 48.21, longitude: 16.37), timeZone: "Europe/Vienna"),
        City(name: "Warsaw", coordinate: .init(latitude: 52.23, longitude: 21.01), timeZone: "Europe/Warsaw"),
        City(name: "Wellington", coordinate: .init(latitude: -41.29, longitude: 174.78), timeZone: "Pacific/Auckland"),
        City(name: "Wichita", coordinate: .init(latitude: 37.69, longitude: -97.34), timeZone: "America/Chicago"),
        City(name: "Winston-Salem", coordinate: .init(latitude: 36.10, longitude: -80.24), timeZone: "America/New_York"),
        City(name: "Zurich", coordinate: .init(latitude: 47.38, longitude: 8.54), timeZone: "Europe/Zurich"),
    ]
}
